general:
    folder_output: outputs
    fname_output: refturb_output

design_variables:
    floating:
        joints:
            flag: True
            z_coordinate:
                - names: [spar_keel]
                  lower_bound: -40.0
                  upper_bound: -15.0
                - names: [spar_freeboard]
                  lower_bound: -40.0
                  upper_bound: -15.0
        members:
            flag: True
            groups:
                - names: [spar]
                  ballast:
                      lower_bound: 1.0
                      upper_bound: 1e4

merit_figure: inverse_design

inverse_design:
    val0:
        name: floatingse.platform_mass
        ref_value: 6.e6

driver:
    optimization:
        flag: True         # Flag to enable optimization
        tol: 1.e-2          # Optimality tolerance
        max_iter: 100         # Maximum number of iterations (SLSQP)
        solver: SNOPT       # Optimization solver. Other options are 'SLSQP' - 'CONMIN'
        step_size: 1.e-3    # Step size for finite differencing
        form: central       # Finite differencing mode, either forward or central
