name: CI_WISDEM

# We run CI on push commits and pull requests on all branches
on: [push, pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    name: Build (${{ matrix.os }} Python ${{ matrix.python-version }})
    runs-on: ${{ matrix.os }}

    defaults:
        run:
            shell: bash -el {0}


    strategy:
      fail-fast: False
      matrix:
        os: [ubuntu-latest, windows-latest] #macos-latest, 
        python-version: ["3.9", "3.10", "3.11"]

    steps:
      #- name: Setup GNU Fortran
      #  uses: modflowpy/install-gfortran-action@v1
        
      - name: checkout repository
        uses: actions/checkout@v3

      - name: Install mamba
        uses: mamba-org/setup-micromamba@v1
        # https://github.com/mamba-org/setup-micromamba
        with:
            environment-file: environment.yml
            environment-name: wisdem-actions
            init-shell: bash powershell
            post-cleanup: 'all'
      #- name: Install conda/mamba
      #  uses: conda-incubator/setup-miniconda@v2
      #  # https://github.com/marketplace/actions/setup-miniconda
      #  with:
      #    #miniconda-version: "latest"
      #    #miniforge-version: "latest"
      #    mamba-version: "*"
      #    channels: conda-forge
      #    channel-priority: true          
      #    #auto-update-conda: true
      #    python-version: ${{ matrix.python-version }}
      #    environment-file: environment.yml
      #    activate-environment: test
      #    auto-activate-base: false

      # Install dependencies of WEIS specific to ubuntu
      - name: Add dependencies ubuntu specific
        if: false == contains( matrix.os, 'windows')
        run: |
          micromamba install -y petsc4py gfortran
          micromamba info
        shell: micromamba-shell {0}

      # Install dependencies of WISDEM specific to windows
      - name: Add dependencies windows specific
        if: contains( matrix.os, 'windows')
        run: |
          micromamba activate wisdem-actions
          micromamba install -y m2w64-toolchain libpython

      - name: Debug config
        run: |
          micromamba list
          which gfortran
        shell: micromamba-shell {0}
    
      # Debugging session
      #- name: Setup tmate session
      #  uses: mxschmitt/action-tmate@v3

      # Install WISDEM with setup
      #- name: Install WISDEM with setup
      #  run: |
      #    pip install -vv --no-deps -e .

      # Install WISDEM with pip
      - name: Install WISDEM with pip for Unix
        if: false == contains( matrix.os, 'windows')
        run: |
          pip install -vv --no-deps -e .
        shell: micromamba-shell {0}

      # Install WISDEM with pip
      - name: Install WISDEM with pip for Windows
        if: contains( matrix.os, 'windows')
        env:
            FC: 'gfortran.exe'
        run: |
            micromamba activate wisdem-actions
            pip install -vv --no-deps .
            which gfortran.exe

      # Run all tests
      - name: Run tests
        if: false == contains( matrix.os, 'windows')
        run: |
          pytest --cov=wisdem
        shell: micromamba-shell {0}

      # Run limited test on WINDOWS
      - name: Limited Windows test
        if: contains( matrix.os, 'windows')
        run: |
          micromamba activate wisdem-actions
          cd wisdem/test/test_gluecode
          pytest test_g*

      # Run coveralls
      - name: Run coveralls
        if: contains( matrix.os, 'ubuntu')
        # This also works, https://github.com/AndreMiras/coveralls-python-action
        #uses: AndreMiras/coveralls-python-action@develop
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          coveralls --service=github
        shell: micromamba-shell {0}
